apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: serving-video-download
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: pratikmahajan/serving-video-download:dev5
            env:
              - name: T_CONSUMER_KEY
                valueFrom:
                  secretKeyRef:
                    key: T_CONSUMER_KEY
                    name: twitter-serverless-events-secret
              - name: T_CONSUMER_SECRET
                valueFrom:
                  secretKeyRef:
                    key: T_CONSUMER_SECRET
                    name: twitter-serverless-events-secret
              - name: T_ACCESS_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: T_ACCESS_TOKEN
                    name: twitter-serverless-events-secret
              - name: T_ACCESS_SECRET
                valueFrom:
                  secretKeyRef:
                    key: T_ACCESS_SECRET
                    name: twitter-serverless-events-secret
              - name: SELF_HANDLE
                valueFrom:
                  secretKeyRef:
                    key: SELF_HANDLE
                    name: twitter-serverless-events-secret